name: GambitRemastered
version: '${project.version}'
main: me.opd.gambitremastered.GambitRemastered
api-version: '1.21'
depend:
  - WorldBorderAPI
softdepend: [ PlaceholderAPI ]
commands:
  gteam:
  start:
  savelocation:
  abort:
  token: